### ISSUE TITLE
yaml viewer & editor

### ISSUE THREAD

**Issue by 1000TurquoisePogs** [zowe/zen#10]
I like the idea of having entries in the schema mapped to html forms, but there are times you need to just see the whole yaml.

Consider,
* someone already knows what to do (they took a backup?) and just want to paste in some yaml
* there's some bug (?) and just editing the yaml is a workaround
* for some reason, there's some entry not covered in the schema yet but it does exist, and so the only way to edit it is via the yaml

In any case, allowing the user to see the whole zowe.yaml and edit it is good.

If we're going to have a yaml editor, I think it should be monaco because
* monaco has yaml syntax highlighting
* monaco is what we already use elsewhere (vscode, desktop editor)
* monaco has some library support for doing schema validation (https://github.com/zowe/zlux-editor/pull/261)

Imagine that every page in zen that prompts you for a property that exists in the yaml is getting/setting some internally managed yaml.
At any step in zen, it should be able to switch to the yaml viewer.
That way, regardless of what page you're on, you could fix or override whatever you need to in the yaml, and then the page you're on should respect the change.

**Comment by skurnevich** [comment]
We planned to have monaco editor at the last step to allow user to see and edit completed zowe.yaml, but i like the idea to have a switch to the yaml viewer on every step as well

**Comment by 1000TurquoisePogs** [comment]
Done by @sakshibobade21
