### ISSUE TITLE
organize steps to align with `zwe` steps

### ISSUE THREAD

**Issue by 1000TurquoisePogs** [zowe/zen#11]
zen currently vaguely follows `zwe` steps but we may want to review and chart out keeping zen as close to zwe as possible.

consider:
upload/extract is to get zwe
zwe install installs.
zwe init breaks down into the subcommands like certificates
`zwe validate` validates schema (could be useful)
`zwe component install` installs extensions (we could add this to zen as a different page - instead of just installing zowe, a post-install could be to install extensions)

**Comment by skurnevich** [comment]
I believe we do follow general zwe steps - **install, init, validate**. 

We do not follow `zwe init` **subcommands** steps strictly in UI, as these are tricky, some could be done manually by other role, some could be omitted at all. 

`zwe component install` - extensions installation is part of Zowe managing process that is done separately, i believe we will have that in Zen, but as you mentioned it is "post-install" actions, and will be handled separately. 
And here, as part of same post install flow, it would be good to give user ability to re-run some particular zwe init subcommand if needed.

**Comment by DivergentEuropeans** [comment]
@skurnevich @1000TurquoisePogs 
> zwe component install - extensions installation is part of Zowe managing process that is done separately, i believe we will have that in Zen, but as you mentioned it is "post-install" actions, and will be handled separately.

I agree + the Zowe App store is under development and will be able to accomplish this too. So it would be useful to have in Zen, but arguably lower priority than the other zwe steps mentioned

**Comment by 1000TurquoisePogs** [comment]
i think we need to do the zwe init subcommands, since thats where you run into permission issues where an individual subcommand could fail, and then need an admin to do them for you.


in fact, at some companies, when you run `zwe init security` or similar, the person who runs the command may get an angry email from admins saying "why are you trying to do all of these restricted things???"
so, we should probably have a page that says "ZEN Is about to do a task that requires an admin. Do you want to proceeed? Or, if not, here's the JCL to send to your admin for them to do it instead."

**Comment by 1000TurquoisePogs** [comment]
Lets draw a mockup for what this might look like before we go implementing anything.

**Comment by 1000TurquoisePogs** [comment]
Complete.
