### ISSUE TITLE
Choice of install file

### ISSUE THREAD

**Issue by 1000TurquoisePogs** [zowe/zen#7]
The current code just fetches zowe as a pax from jfrog automatically, and then installs it.
but there are reasons why this shouldn't be done
* legal. users are supposed to agree to some terms & conditions before the download happens if it comes from zowe
* internet access. users may not be able to, by policy or configuration, access jfrog
* contract/preference: some users may be getting zowe from their support vendors. they may have a requirement to only download zos content from certain sites.
* type: users may want smpe or pswi installs

A solution could be a download page as a step in the installer.
* ask users whether they want to install by picking a file on their computer, or by fetching from a site they type in, or by zowe's own download (fully automatic after a consent page)
* have the users pick whether the file is pax/smpe/pswi, which will influence the install process

**Comment by DivergentEuropeans** [comment]
@timgerstel began work on this via File Uploader

**Comment by 1000TurquoisePogs** [comment]
Complete
