### ISSUE TITLE
UI enhancements / concerns

### ISSUE THREAD

**Issue by 1000TurquoisePogs** [zowe/zen#78]
New UI for showing progress when many steps

Today ZEN has about 7 steps, but one of the steps is very big so we want to split it into each zwe subcommand. That's going to end up with maybe 14+ steps.

Some ideas to solve this problem might be:

2-dimensional
```
<install step> **<init step>** <verify step>
<init mvs> <init security> **<init certificate>** <init vsam>
```

1-dimensional tracking relatively
```
<last step> <current step> <next step>
```

This last idea requires a percentage bar to know how close you are to complete.
Maybe we should have one regardless.

**Comment by 1000TurquoisePogs** [comment]
Question about where buttons go

Buttons like "next" or "cancel", "submit" or "preview" or "dry run" all seem like they could show up on any/every page. I imagine they should go in a certain location for every page to be easy to understand.
But, the bottom bar is becoming very full.

There's also advanced / settings actions like to view yaml or to export/import yaml/jcl
Those might go on a top bar? we dont really have one yet, should we make one?

**Comment by DivergentEuropeans** [comment]
We added a substepper which is about 1/2 this ticket or more. The buttons are a WIP, they're in an okay state now, but each button change should probably be addressed on case by case so I'll close for now, will fill out backlog
