### ISSUE TITLE
Step 2 should show space required for Zen to install Zowe

### ISSUE THREAD

**Issue by DivergentEuropeans** [zowe/zen#80]
![image](https://github.com/zowe/zen/assets/20528015/3c3c0fb6-3947-4e2b-b1e5-5e31a8559d90)

doesn't show space required unless you have ENOUGH.

**Comment by jainkunal40** [comment]
I can work on this, Can someone assign this to me?

**Comment by DivergentEuropeans** [comment]
We removed the space check because space on ZFS is dynamic. you can have more space than USS thinks.
